version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: techdukkan-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: techdukkan-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: